-- ============================================
-- Migration 006 : (obsolète)
-- Le backfill des genres est géré directement
-- dans l'API Next.js via le service role key.
-- Aucune action SQL requise pour cette migration.
-- ============================================
